project:
  type: website

website:
  title: "LearningByDoing"
 
  sidebar:
      style: "floating"
      search: true
      collapse-level: 2
      alignment: left

      contents:
      - section: "1 Complex Heatmap"
        href: 01_Heatmap_Genomics/1_ComplexHeatmap/1ComplexHeatmap.Rmd
      - section: "2 DE Heatmap"
        href: 01_Heatmap_Genomics/2_DE_Heatmap/scripts/2DE_Heatmap.qmd
