project:
  type: website

format:
  html:
    include-after-body:
      - after-body.html

website:
  title: "- - - - - -  LearningByDoing"

  navbar: {}  
 
  sidebar:
      style: "floating"
      search: true
      collapse-level: 2
      alignment: left

      contents:
        - section: "Heatmap"
          contents:
            - text: "ComplexHeatmap"
              href: "01_Heatmap_Genomics/1_ComplexHeatmap/1ComplexHeatmap.Rmd"
          
            - text: "DE Heatmap" 
              href: "01_Heatmap_Genomics/2_DE_Heatmap/scripts/2DE_Heatmap.qmd"
