name: bioinfo
channels:
  - bioconda
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - anyio=4.11.0
  - appnope=0.1.4
  - argcomplete=3.6.3
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asttokens=3.0.1
  - async-lru=2.0.5
  - attrs=25.4.0
  - babel=2.17.0
  - beautifulsoup4=4.14.2
  - bioconductor-biobase=2.66.0
  - bioconductor-biocgenerics=0.52.0
  - bioconductor-biocparallel=1.40.0
  - bioconductor-data-packages=20250625
  - bioconductor-delayedarray=0.32.0
  - bioconductor-deseq2=1.46.0
  - bioconductor-genomeinfodb=1.42.0
  - bioconductor-genomeinfodbdata=1.2.13
  - bioconductor-genomicranges=1.58.0
  - bioconductor-iranges=2.40.0
  - bioconductor-matrixgenerics=1.18.0
  - bioconductor-s4arrays=1.6.0
  - bioconductor-s4vectors=0.44.0
  - bioconductor-sparsearray=1.6.0
  - bioconductor-summarizedexperiment=1.36.0
  - bioconductor-ucsc.utils=1.2.0
  - bioconductor-xvector=0.46.0
  - bioconductor-zlibbioc=1.52.0
  - biopython=1.86
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - brotli-python=1.2.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - cctools_osx-64=1024.3
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - clang=21.1.0
  - clang-21=21.1.0
  - clang_impl_osx-64=21.1.0
  - clang_osx-64=21.1.0
  - clangxx=21.1.0
  - clangxx_impl_osx-64=21.1.0
  - clangxx_osx-64=21.1.0
  - comm=0.2.3
  - compiler-rt=21.1.0
  - compiler-rt_osx-64=21.1.0
  - csvtk=0.36.0
  - curl=8.17.0
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fqdn=1.5.1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gfortran_impl_osx-64=14.3.0
  - gfortran_osx-64=14.3.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - gsl=2.7
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=12.2.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=7.1.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - isl=0.26
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jq=1.8.1
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.5.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - krb5=1.21.3
  - lark=1.3.1
  - ld64_osx-64=955.13
  - lerc=4.0.0
  - libasprintf=0.25.1
  - libblas=3.11.0
  - libcblas=3.11.0
  - libclang-cpp21.1=21.1.0
  - libcurl=8.17.0
  - libcxx=21.1.6
  - libcxx-devel=21.1.6
  - libcxx-headers=21.1.6
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgettextpo=0.25.1
  - libgfortran=15.2.0
  - libgfortran-devel_osx-64=14.3.0
  - libgfortran5=15.2.0
  - libglib=2.86.2
  - libiconv=1.18
  - libintl=0.25.1
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - libllvm21=21.1.0
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libsodium=1.0.20
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libtiff=4.7.1
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=21.1.6
  - llvm-tools=21.1.0
  - llvm-tools-21=21.1.0
  - make=4.4.1
  - markupsafe=3.0.3
  - matplotlib-inline=0.2.1
  - mistune=3.1.4
  - mpc=1.3.1
  - mpfr=4.2.1
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook=7.5.0
  - notebook-shim=0.2.4
  - numpy=2.3.5
  - oniguruma=6.9.10
  - openssl=3.6.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandoc=3.6.3
  - pandocfilters=1.5.0
  - pango=1.56.4
  - parso=0.8.5
  - pcre2=10.46
  - pexpect=4.9.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.0
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pyobjc-core=12.1
  - pyobjc-framework-cocoa=12.1
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - r-abind=1.4_8
  - r-askpass=1.2.1
  - r-assertthat=0.2.1
  - r-backports=1.5.0
  - r-base=4.4.3
  - r-base64enc=0.1_3
  - r-bh=1.87.0_1
  - r-biocmanager=1.30.27
  - r-bit=4.6.0
  - r-bit64=4.6.0_1
  - r-blob=1.2.4
  - r-boot=1.3_32
  - r-broom=1.0.10
  - r-bslib=0.9.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-caret=7.0_1
  - r-cellranger=1.1.0
  - r-class=7.3_23
  - r-cli=3.6.5
  - r-clipr=0.8.0
  - r-clock=0.7.3
  - r-cluster=2.1.8.1
  - r-codetools=0.2_20
  - r-colorspace=2.1_2
  - r-commonmark=2.0.0
  - r-conflicted=1.2.0
  - r-cpp11=0.5.2
  - r-crayon=1.5.3
  - r-crul=1.6.0
  - r-curl=7.0.0
  - r-data.table=1.17.8
  - r-dbi=1.2.3
  - r-dbplyr=2.5.1
  - r-diagram=1.6.5
  - r-digest=0.6.39
  - r-dplyr=1.1.4
  - r-dtplyr=1.3.2
  - r-e1071=1.7_16
  - r-ellipsis=0.3.2
  - r-essentials=4.4
  - r-evaluate=1.0.5
  - r-fansi=1.0.7
  - r-farver=2.1.2
  - r-fastmap=1.2.0
  - r-fontawesome=0.5.3
  - r-forcats=1.0.1
  - r-foreach=1.5.2
  - r-foreign=0.8_90
  - r-formatr=1.14
  - r-fs=1.6.6
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-future=1.68.0
  - r-future.apply=1.20.0
  - r-gargle=1.6.0
  - r-generics=0.1.4
  - r-ggplot2=4.0.1
  - r-ggrepel=0.9.6
  - r-gistr=0.9.0
  - r-glmnet=4.1_10
  - r-globals=0.18.0
  - r-glue=1.8.0
  - r-googledrive=2.1.2
  - r-googlesheets4=1.1.2
  - r-gower=1.0.1
  - r-gtable=0.3.6
  - r-hardhat=1.4.2
  - r-haven=2.5.5
  - r-here=1.0.2
  - r-hexbin=1.28.5
  - r-highr=0.11
  - r-hms=1.1.4
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.4
  - r-httpcode=0.3.0
  - r-httpuv=1.6.16
  - r-httr=1.4.7
  - r-ids=1.0.1
  - r-ipred=0.9_15
  - r-irdisplay=1.1
  - r-irkernel=1.3.2
  - r-isoband=0.2.7
  - r-iterators=1.0.14
  - r-jquerylib=0.1.4
  - r-jsonlite=2.0.0
  - r-kernsmooth=2.23_26
  - r-knitr=1.50
  - r-labeling=0.4.3
  - r-lambda.r=1.2.4
  - r-later=1.4.4
  - r-lattice=0.22_7
  - r-lava=1.8.2
  - r-lazyeval=0.2.2
  - r-lifecycle=1.0.4
  - r-listenv=0.10.0
  - r-lobstr=1.1.3
  - r-locfit=1.5_9.12
  - r-lubridate=1.9.4
  - r-magrittr=2.0.4
  - r-maps=3.4.3
  - r-mass=7.3_65
  - r-matrix=1.7_4
  - r-matrixstats=1.5.0
  - r-memoise=2.0.1
  - r-mgcv=1.9_4
  - r-mime=0.13
  - r-modelmetrics=1.2.2.2
  - r-modelr=0.1.11
  - r-munsell=0.5.1
  - r-nlme=3.1_168
  - r-nnet=7.3_20
  - r-numderiv=2016.8_1.1
  - r-openssl=2.3.4
  - r-otel=0.2.0
  - r-parallelly=1.45.1
  - r-pbdzmq=0.3_14
  - r-pillar=1.11.1
  - r-pkgconfig=2.0.3
  - r-plyr=1.8.9
  - r-prettyunits=1.2.0
  - r-proc=1.19.0.1
  - r-processx=3.8.6
  - r-prodlim=2025.04.28
  - r-progress=1.2.3
  - r-progressr=0.18.0
  - r-promises=1.5.0
  - r-proxy=0.4_27
  - r-pryr=0.1.6
  - r-ps=1.9.1
  - r-purrr=1.2.0
  - r-quantmod=0.4.28
  - r-r6=2.6.1
  - r-ragg=1.5.0
  - r-randomforest=4.7_1.2
  - r-rappdirs=0.3.3
  - r-rbokeh=0.5.2
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.1.0
  - r-rcpparmadillo=15.2.2_1
  - r-rcppeigen=0.3.4.0.2
  - r-readr=2.1.6
  - r-readxl=1.4.5
  - r-recipes=1.3.1
  - r-recommended=4.4
  - r-rematch=2.0.0
  - r-rematch2=2.1.2
  - r-repr=1.1.7
  - r-reprex=2.1.1
  - r-reshape2=1.4.5
  - r-rlang=1.1.6
  - r-rmarkdown=2.30
  - r-rpart=4.1.24
  - r-rprojroot=2.1.1
  - r-rstudioapi=0.17.1
  - r-rvest=1.0.5
  - r-s7=0.2.1
  - r-sass=0.4.10
  - r-scales=1.4.0
  - r-selectr=0.5_0
  - r-shape=1.4.6.1
  - r-shiny=1.11.1
  - r-snow=0.4_4
  - r-sourcetools=0.1.7_1
  - r-sparsevctrs=0.3.4
  - r-spatial=7.3_18
  - r-squarem=2021.1
  - r-stringi=1.8.7
  - r-stringr=1.6.0
  - r-survival=3.8_3
  - r-sys=3.4.3
  - r-systemfonts=1.3.1
  - r-textshaping=1.0.4
  - r-tibble=3.3.0
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-tidyverse=2.0.0
  - r-timechange=0.3.0
  - r-timedate=4051.111
  - r-tinytex=0.58
  - r-triebeard=0.4.1
  - r-ttr=0.24.4
  - r-tzdb=0.5.0
  - r-urltools=1.7.3.1
  - r-utf8=1.2.6
  - r-uuid=1.2_1
  - r-vctrs=0.6.5
  - r-viridislite=0.4.2
  - r-vroom=1.6.6
  - r-withr=3.0.2
  - r-xfun=0.54
  - r-xml2=1.4.0
  - r-xtable=1.8_4
  - r-xts=0.14.1
  - r-yaml=2.3.10
  - r-zoo=1.8_14
  - readline=8.2
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.29.0
  - send2trash=1.8.3
  - setuptools=80.9.0
  - sigtool=0.1.3
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.8
  - stack_data=0.6.3
  - tapi=1300.6.5
  - terminado=0.18.1
  - tinycss2=1.5.0
  - tk=8.6.13
  - tktable=2.10
  - toml=0.10.2
  - tomli=2.3.0
  - tomlkit=0.13.3
  - tornado=6.5.2
  - traitlets=5.14.3
  - tree=2.2.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - uri-template=1.3.0
  - urllib3=2.5.0
  - wcwidth=0.2.14
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - wheel=0.45.1
  - xmltodict=1.0.2
  - yaml=0.2.5
  - yq=3.4.3
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7

prefix: "/Users/user/.local/share/mamba/envs/bioinfo"
